[dependency.bash]
optional = false
on_level = "Node" # Node | Cluster | Project | Client
collection = "Executor"

[dependency.python]
optional = false
on_level = "Node" # Node | Cluster | Project | Client
optional_with = ["bash"]
collection = "Executor"
